enable retrieval of GTIDs via Conn and Transaction
readysettech/mysql_async pull request #1
Opened 2021-04-01 00:54 UTC by a-tsakiris85

## Overview
Giving the user access to GTIDs from OK packets acking commits involves
two main changes.

1) enabling configuration of capability flags for Opts
so that CLIENT_SESSION_TRACK can be enabled. 

2) adding a new public
method to Conn to retrieve the session state change information.

## Known Issues
I played around awhile with the changes in mod.rs, but let me know if there is a more idiomatic way to do what I'm doing.
The testing assumes that the database is configured properly, but I didn't actually make changes to the azure pipeline stuff since that seemed like not a great immediate use of my time.

## Testing
New unit test passes with properly configured database.
Also tested manually with our client and it works!

2021-04-01 00:55 UTC, a-tsakiris85 commented
@glittershark tagging you here in case you wanted to take a look at this new fork and the changes.

2021-04-01 00:57 UTC, a-tsakiris85 commented on src/conn/mod.rs
> +
This matched as closely as possible to the info() method already existing in the library, but it still seems a little messy. 
I also could simply not get past the rust compiler with returning a Cow, so i have it returning a String, which seems fine to me for now :shrug: 

Open to suggestions on how to make this nicer

2021-04-01 01:41 UTC, glittershark commented on src/conn/mod.rs
> +                                mysql_common::packets::SessionStateChange::UnknownLayout(data) => Some(String::from_utf8_lossy(data.as_ref()).to_string()),
![](https://static.independent.co.uk/2020/09/22/09/Untitled.png?width=1200)

2021-04-01 01:42 UTC, glittershark commented on src/conn/mod.rs
> +
I can help you Cow if you like

2021-04-01 14:45 UTC, glittershark requested changes

2021-04-01 14:45 UTC, glittershark commented on src/conn/mod.rs
> +                                mysql_common::packets::SessionStateChange::UnknownLayout(data) => Some(String::from_utf8_lossy(data.as_ref()).to_string()),
can we rustfmt this?

2021-04-01 14:45 UTC, glittershark commented on src/queryable/transaction.rs
> +    pub async fn commit_and_gtid(mut self) -> Result<String> {
`commit_returning_gtid`, perhaps?

2021-04-01 14:45 UTC, glittershark commented on src/conn/mod.rs
> +        ).unwrap_or_else(|| "".into())
wouldn't it be better to have this return an `Option`?

2021-04-01 14:45 UTC, glittershark commented on src/conn/mod.rs
> +
but also returning a String seems semantically fine to me here.

2021-04-01 14:45 UTC, glittershark commented on src/conn/mod.rs
> +                                mysql_common::packets::SessionStateChange::UnknownLayout(data) => Some(String::from_utf8_lossy(data.as_ref()).to_string()),
we're calling `to_string()` on the result of a `String::from`, which feels unnecessary to me.

Also re the from_utf8_lossy stuff - I'm not sure what the semantics of gtids are, but are we really guaranteed that they'll always be valid utf8? if so I'm worried we're going to get a data mismatch here

2021-04-01 19:13 UTC, jmiron11 commented
will take a look after griffin's comments are addressed

2021-04-01 20:28 UTC, a-tsakiris85 commented on src/conn/mod.rs
> +        ).unwrap_or_else(|| "".into())
Yeah, at first I was just trying to follow the format of the existing methods, but I am just going to use Option since it makes more sense

2021-04-01 20:30 UTC, a-tsakiris85 commented on src/conn/mod.rs
> +                                mysql_common::packets::SessionStateChange::UnknownLayout(data) => Some(String::from_utf8_lossy(data.as_ref()).to_string()),
I think we are OK here since the mysql-common crate handles the representation of the OK packet and the GTIDs are [u8]. Im not sure why they would not be valid but its possible I am not thinking of something. We also want to convert them to strings since their string form has meaning -- <serverid>:<txid>

2021-04-01 20:31 UTC, a-tsakiris85 commented on src/conn/mod.rs
> +                                mysql_common::packets::SessionStateChange::UnknownLayout(data) => Some(String::from_utf8_lossy(data.as_ref()).to_string()),
String::from_utf_lossy returns a Cow, so was using to_string() to convert to a normal String. Not sure if that's the right thing to do but...

2021-04-01 21:47 UTC, glittershark approved these changes

2021-04-01 22:02 UTC, a-tsakiris85 commented
> will take a look after griffin's comments are addressed

@jmiron11 feel free to take a look when you get the chance

2021-04-02 16:58 UTC, jmiron11 approved these changes
nice

2021-04-02 17:02 UTC, merged